// <auto-generated />
using System;
using Blog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blog2023.Migrations.ApplicationDbContextAddressMigrations
{
    [DbContext(typeof(ApplicationDbContextAddress))]
    partial class ApplicationDbContextAddressModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blog2023.Data.Models.As_addr_obj", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long?>("changeid")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("enddate")
                        .HasColumnType("date");

                    b.Property<int?>("isactive")
                        .HasColumnType("integer");

                    b.Property<int?>("isactual")
                        .HasColumnType("integer");

                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("nextid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<int?>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<long?>("previd")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("startdate")
                        .HasColumnType("date");

                    b.Property<string>("typename")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_addr_obj");
                });

            modelBuilder.Entity("Blog2023.Data.Models.as_adm_hierarchy", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("areacode")
                        .HasColumnType("text");

                    b.Property<long?>("changeid")
                        .HasColumnType("bigint");

                    b.Property<string>("citycode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("enddate")
                        .HasColumnType("date");

                    b.Property<int?>("isactive")
                        .HasColumnType("integer");

                    b.Property<long?>("nextid")
                        .HasColumnType("bigint");

                    b.Property<long?>("objectid")
                        .HasColumnType("bigint");

                    b.Property<long?>("parentobjid")
                        .HasColumnType("bigint");

                    b.Property<string>("path")
                        .HasColumnType("text");

                    b.Property<string>("placecode")
                        .HasColumnType("text");

                    b.Property<string>("plancode")
                        .HasColumnType("text");

                    b.Property<long?>("previd")
                        .HasColumnType("bigint");

                    b.Property<string>("regioncode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("startdate")
                        .HasColumnType("date");

                    b.Property<string>("streetcode")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_adm_hierarchy");
                });

            modelBuilder.Entity("Blog2023.Data.Models.as_houses", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("addnum1")
                        .HasColumnType("text");

                    b.Property<string>("addnum2")
                        .HasColumnType("text");

                    b.Property<int?>("addtype1")
                        .HasColumnType("integer");

                    b.Property<int?>("addtype2")
                        .HasColumnType("integer");

                    b.Property<long?>("changeid")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("enddate")
                        .HasColumnType("date");

                    b.Property<string>("housenum")
                        .HasColumnType("text");

                    b.Property<int?>("housetype")
                        .HasColumnType("integer");

                    b.Property<int?>("isactive")
                        .HasColumnType("integer");

                    b.Property<int?>("isactual")
                        .HasColumnType("integer");

                    b.Property<long?>("nextid")
                        .HasColumnType("bigint");

                    b.Property<Guid>("objectguid")
                        .HasColumnType("uuid");

                    b.Property<long>("objectid")
                        .HasColumnType("bigint");

                    b.Property<int?>("opertypeid")
                        .HasColumnType("integer");

                    b.Property<long?>("previd")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("startdate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("updatedate")
                        .HasColumnType("date");

                    b.HasKey("id");

                    b.ToTable("as_houses");
                });
#pragma warning restore 612, 618
        }
    }
}
